-- Seed California cities for onboarding and team grouping.
-- Safe to run multiple times.
insert into public.cities (name, state, region, country, country_code)
select
  v.city_name,
  'California',
  'CA',
  'United States',
  'US'
from (
  values
    ('Los Angeles'),
    ('San Diego'),
    ('San Jose'),
    ('San Francisco'),
    ('Fresno'),
    ('Sacramento'),
    ('Long Beach'),
    ('Oakland'),
    ('Bakersfield'),
    ('Anaheim'),
    ('Santa Ana'),
    ('Riverside'),
    ('Stockton'),
    ('Irvine'),
    ('Chula Vista'),
    ('Fremont'),
    ('San Bernardino'),
    ('Modesto'),
    ('Fontana'),
    ('Oxnard'),
    ('Moreno Valley'),
    ('Huntington Beach'),
    ('Glendale'),
    ('Santa Clarita'),
    ('Garden Grove'),
    ('Oceanside'),
    ('Rancho Cucamonga'),
    ('Santa Rosa'),
    ('Ontario'),
    ('Elk Grove'),
    ('Corona'),
    ('Lancaster'),
    ('Palmdale'),
    ('Salinas'),
    ('Hayward'),
    ('Pomona'),
    ('Escondido'),
    ('Sunnyvale'),
    ('Torrance'),
    ('Pasadena'),
    ('Fullerton'),
    ('Orange'),
    ('Thousand Oaks'),
    ('Visalia'),
    ('Simi Valley'),
    ('Concord'),
    ('Roseville'),
    ('Victorville'),
    ('Santa Clara'),
    ('Vallejo'),
    ('Berkeley'),
    ('El Monte'),
    ('Downey'),
    ('Costa Mesa'),
    ('Inglewood'),
    ('Ventura'),
    ('West Covina'),
    ('Fairfield'),
    ('Norwalk'),
    ('Carlsbad'),
    ('Antioch'),
    ('Murrieta'),
    ('Richmond'),
    ('Burbank'),
    ('Temecula'),
    ('Santa Maria'),
    ('Santa Monica'),
    ('Clovis'),
    ('Redding'),
    ('Santa Barbara'),
    ('San Mateo'),
    ('Yuba City')
) as v(city_name)
on conflict do nothing;
